### ISSUE TITLE
Add mutations

### ISSUE THREAD

**Issue by juffalow** [juffalow/slim-graphql-eloquent-example#2]
Add mutations so that user is able to add new data or update existing.

**Comment by sheikalthaf** [comment]
@juffalow will you please add mutations to this repo?

**Comment by juffalow** [comment]
Hi @sheikalthaf! Yes, but give me one day, because I do not have time right now. If you need it asap, I can write you how you can add them or send you some example files from other project.

**Comment by sheikalthaf** [comment]
@juffalow I'm currently learning for one of my projects.
Already REST API available and now I'm converting it into graphql.
if possible jwt implementaion also in graphql.
Please send me if possible

Thanks in advance
